version: "3"
services:
  app:
    build: .
    container_name: calculator
    ports:
      - 5000:5000
      - 5001:5001
      - 8089:8089
    volumes:
      - ./app:/app
      - ./app/log:/app/log

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=history_db
    volumes:
      - ./database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d